a = float(input("Informe o valor do a:"))
b = float(input("Informe o valor do b:"))
c = float(input("Informe o valor do c:"))
d = float(input("Informe o valor do d:"))
e = float(input("Informe o valor do e:"))
f = float(input("Informe o valor do f:"))
x = (c * e - b * f) / (a * e - b * d)
y = (a * f - c * d) / (a * e - b * d)
print(f"Os valores de x e y são, respectivamente:{x:.2f} e {y:.2f}")